export const CACHE_DURATION = 60 * 60 * 1.5;
export const USE_MOCK_DATA_FOR_DEVELOPMENT = true;

export const DEFAULT_BUY_COFFEE_SUBSCRIPTION_RESPONSE: SubscriptionResponse = {
  current_page: 1,
  data: [
    {
      subscription_id: 10647,
      subscription_cancelled_on: null,
      subscription_created_on: "2020-07-29 15:15:22",
      subscription_updated_on: "2020-07-29 15:15:22",
      subscription_current_period_start: "2020-07-29 15:15:18",
      subscription_current_period_end: "2020-08-29 15:15:18",
      subscription_coffee_price: "1.000",
      subscription_coffee_num: 1,
      subscription_is_cancelled: null,
      subscription_is_cancelled_at_period_end: null,
      subscription_currency: "USD",
      subscription_message: null,
      message_visibility: 1,
      subscription_duration_type: "month",
      referer: null,
      country: null,
      transaction_id: "sub_HjkUcn*******",
      payer_email: "ronald.thyu@gmail.org",
      payer_name: "ronald.thomas",
    },
  ],
  first_page_url:
    "https://developers.buymeacoffee.com/api/v1/subscriptions?page=1",
  from: 1,
  last_page: 36,
  last_page_url:
    "https://developers.buymeacoffee.com/api/v1/subscriptions?page=36",
  next_page_url:
    "https://developers.buymeacoffee.com/api/v1/subscriptions?page=2",
  path: "https://developers.buymeacoffee.com/api/v1/subscriptions",
  per_page: 5,
  prev_page_url: null,
  to: 5,
  total: 179,
};

export const DEFAULT_BUY_COFFEE_SUPPORTERS_RESPONSE: SupporterResponse = {
  current_page: 1,
  data: [
    {
      support_id: 8808523,
      support_note: "Thanks for creating cool products.",
      support_coffees: 1,
      transaction_id: "pi_3QQQUrJEtINljGAa0iRaB6gd",
      support_visibility: 1,
      support_created_on: "2024-11-29 09:28:54",
      support_updated_on: "2024-11-29 09:28:54",
      transfer_id: null,
      supporter_name: "frkn",
      support_coffee_price: "5.0000",
      support_email: null,
      is_refunded: null,
      support_currency: "USD",
      support_type: 1,
      referer: null,
      country: "TR",
      order_payload: '{"widget_version": 1, "posthog_variant": ""}',
      support_hidden: 0,
      refunded_at: null,
      payer_email: "frknbasaran@gmail.com",
      payment_platform: "stripe",
      payer_name: "frkn",
    },
    {
      support_id: 7400091,
      support_note: null,
      support_coffees: 1,
      transaction_id: "pi_3PYN7dJEtINljGAa1gEYzKyF",
      support_visibility: 1,
      support_created_on: "2024-07-03 06:57:25",
      support_updated_on: "2024-07-03 06:57:25",
      transfer_id: null,
      supporter_name: "@omarkurt",
      support_coffee_price: "5.0000",
      support_email: null,
      is_refunded: null,
      support_currency: "USD",
      support_type: 1,
      referer: null,
      country: "TR",
      order_payload: '{"widget_version": 1}',
      support_hidden: 0,
      refunded_at: null,
      payer_email: "omarkurt@pm.me",
      payment_platform: "stripe",
      payer_name: "@omarkurt",
    },
  ],
  first_page_url:
    "https://developers.buymeacoffee.com/api/v1/supporters?page=1",
  from: 1,
  last_page: 1,
  last_page_url: "https://developers.buymeacoffee.com/api/v1/supporters?page=1",
  next_page_url: null,
  path: "https://developers.buymeacoffee.com/api/v1/supporters",
  per_page: 5,
  prev_page_url: null,
  to: 2,
  total: 2,
};
